import { Suggestion, Category, Neighborhood, OfficialResponse, SuggestionStatusHistory, Comment } from './database';

export interface SuggestionWithDetails extends Suggestion {
  category?: Category;
  neighborhood?: Neighborhood;
  official_responses?: OfficialResponse[];
  status_history?: SuggestionStatusHistory[];
  comments?: Comment[];
  is_supported_by_user?: boolean;
  is_followed_by_user?: boolean;
}

export const STATUS_CONFIG: Record<
  string,
  { label: string; color: string; bg: string; description: string; step: number }
> = {
  draft: {
    label: 'Draft',
    color: '#94A3B8',
    bg: 'rgba(148, 163, 184, 0.15)',
    description: 'Saved locally, not yet submitted to council.',
    step: 0,
  },
  submitted: {
    label: 'Submitted',
    color: '#3B82F6',
    bg: 'rgba(59, 130, 246, 0.15)',
    description: 'Received by municipal team and queued for initial triage.',
    step: 1,
  },
  under_review: {
    label: 'Under Review',
    color: '#8B5CF6',
    bg: 'rgba(139, 92, 246, 0.15)',
    description: 'Being evaluated by relevant urban planning & governance staff.',
    step: 2,
  },
  needs_information: {
    label: 'Needs Info',
    color: '#F59E0B',
    bg: 'rgba(245, 158, 11, 0.15)',
    description: 'Staff requested additional clarification from the community.',
    step: 2,
  },
  planned: {
    label: 'Planned',
    color: '#06B6D4',
    bg: 'rgba(6, 182, 212, 0.15)',
    description: 'Approved and integrated into upcoming municipal work budget.',
    step: 3,
  },
  in_progress: {
    label: 'In Progress',
    color: '#EC4899',
    bg: 'rgba(236, 72, 153, 0.15)',
    description: 'Active physical construction, installation, or policy implementation.',
    step: 4,
  },
  completed: {
    label: 'Completed',
    color: '#10B981',
    bg: 'rgba(16, 185, 129, 0.15)',
    description: 'Successfully implemented for public benefit.',
    step: 5,
  },
  closed: {
    label: 'Closed',
    color: '#64748B',
    bg: 'rgba(100, 116, 139, 0.15)',
    description: 'Concluded without action or referred to existing services.',
    step: 5,
  },
  rejected: {
    label: 'Not Actionable',
    color: '#EF4444',
    bg: 'rgba(239, 68, 68, 0.15)',
    description: 'Does not meet civic proposal guidelines or jurisdiction.',
    step: 5,
  },
};

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Mobility & Transit',
    slug: 'mobility-transit',
    description: 'Protected bike lanes, bus shelters, pedestrian safety, and micro-mobility.',
    color_token: '#3B82F6',
    icon_key: 'Bike',
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    name: 'Parks & Green Spaces',
    slug: 'parks-green-spaces',
    description: 'Urban forestry, community gardens, park amenities, and biodiversity.',
    color_token: '#10B981',
    icon_key: 'Trees',
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    name: 'Clean Energy & Environment',
    slug: 'clean-energy-environment',
    description: 'Solar microgrids, waste sorting, composting, and EV charging points.',
    color_token: '#06B6D4',
    icon_key: 'Zap',
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-4',
    name: 'Public Infrastructure',
    slug: 'public-infrastructure',
    description: 'Street lighting, stormwater drainage, sidewalk repair, and accessibility.',
    color_token: '#F59E0B',
    icon_key: 'Building2',
    sort_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-5',
    name: 'Culture & Community',
    slug: 'culture-community',
    description: 'Public art murals, street plazas, outdoor seating, and youth programs.',
    color_token: '#EC4899',
    icon_key: 'HeartHandshake',
    sort_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const SEED_NEIGHBORHOODS: Neighborhood[] = [
  { id: 'neigh-1', name: 'Downtown Core', slug: 'downtown-core', geometry: null, is_active: true, created_at: new Date().toISOString() },
  { id: 'neigh-2', name: 'Waterfront District', slug: 'waterfront-district', geometry: null, is_active: true, created_at: new Date().toISOString() },
  { id: 'neigh-3', name: 'Greenway East', slug: 'greenway-east', geometry: null, is_active: true, created_at: new Date().toISOString() },
  { id: 'neigh-4', name: 'Old Town Square', slug: 'old-town-square', geometry: null, is_active: true, created_at: new Date().toISOString() },
  { id: 'neigh-5', name: 'Highland Park', slug: 'highland-park', geometry: null, is_active: true, created_at: new Date().toISOString() },
];

export const SEED_SUGGESTIONS: SuggestionWithDetails[] = [
  {
    id: 'sug-101',
    author_id: 'usr-1',
    title: 'Protected Solar Bike Highway on Main Street Corridor',
    description: 'Transform the outer lane of Main Street into a physically separated, solar-canopied bicycle and e-scooter path. Includes smart LED lighting and emergency call posts.',
    category_id: 'cat-1',
    neighborhood_id: 'neigh-1',
    category: SEED_CATEGORIES[0],
    neighborhood: SEED_NEIGHBORHOODS[0],
    location: { x: -3.5, y: 0.5, z: 2.1, address: 'Main St & 4th Ave', neighborhood_name: 'Downtown Core' },
    status: 'in_progress',
    visibility: 'public',
    is_anonymous: false,
    support_count: 342,
    comment_count: 28,
    submitted_at: '2026-08-10T10:30:00Z',
    published_at: '2026-08-11T09:00:00Z',
    closed_at: null,
    created_at: '2026-08-10T09:15:00Z',
    updated_at: '2026-08-25T14:20:00Z',
    official_responses: [
      {
        id: 'resp-1',
        suggestion_id: 'sug-101',
        author_id: 'staff-1',
        author_name: 'Municipal Transportation Directorate',
        body: 'Phase 1 engineering study completed. Budget allocation approved in the Q3 Mobility Grant ($180,000). Construction of physical barriers commenced on August 20th.',
        is_published: true,
        published_at: '2026-08-20T16:00:00Z',
        created_at: '2026-08-20T15:45:00Z',
        updated_at: '2026-08-20T16:00:00Z',
      },
    ],
    status_history: [
      { id: 'h-1', suggestion_id: 'sug-101', from_status: 'submitted', to_status: 'under_review', note: 'Assigned to Transportation Committee.', changed_by: 'staff-1', created_at: '2026-08-12T08:00:00Z' },
      { id: 'h-2', suggestion_id: 'sug-101', from_status: 'under_review', to_status: 'planned', note: 'Public support exceeded 250 votes threshold.', changed_by: 'staff-1', created_at: '2026-08-18T11:30:00Z' },
      { id: 'h-3', suggestion_id: 'sug-101', from_status: 'planned', to_status: 'in_progress', note: 'Work crew deployed.', changed_by: 'staff-1', created_at: '2026-08-20T16:00:00Z' },
    ],
    comments: [
      { id: 'c-1', suggestion_id: 'sug-101', author_id: 'usr-2', author_name: 'Elena Rostova', body: 'This will make commuting from Greenway East so much safer for students!', status: 'visible', created_at: '2026-08-12T14:00:00Z', updated_at: '2026-08-12T14:00:00Z' },
      { id: 'c-2', suggestion_id: 'sug-101', author_id: 'usr-3', author_name: 'Marcus Vance', body: 'Please ensure adequate turning radiuses for emergency vehicles at the 4th Ave intersection.', status: 'visible', created_at: '2026-08-15T09:12:00Z', updated_at: '2026-08-15T09:12:00Z' },
    ],
  },
  {
    id: 'sug-102',
    author_id: 'usr-4',
    title: 'Rainwater Harvesting & Native Botanical Pocket Park',
    description: 'Convert the vacant paved lot behind Old Town Square into a bio-swale pocket park featuring native drought-tolerant flora and automated greywater filtration for public fountains.',
    category_id: 'cat-2',
    neighborhood_id: 'neigh-4',
    category: SEED_CATEGORIES[1],
    neighborhood: SEED_NEIGHBORHOODS[3],
    location: { x: 4.1, y: 0.5, z: -1.8, address: 'Old Town Plaza Lot B', neighborhood_name: 'Old Town Square' },
    status: 'planned',
    visibility: 'public',
    is_anonymous: false,
    support_count: 219,
    comment_count: 14,
    submitted_at: '2026-08-05T14:10:00Z',
    published_at: '2026-08-06T10:00:00Z',
    closed_at: null,
    created_at: '2026-08-05T11:00:00Z',
    updated_at: '2026-08-28T10:00:00Z',
    official_responses: [
      {
        id: 'resp-2',
        suggestion_id: 'sug-102',
        author_id: 'staff-2',
        author_name: 'Parks & Recreation Board',
        body: 'Landscape architects have drafted preliminary spatial layouts. Public co-design workshop scheduled for September 15th at the Civic Center.',
        is_published: true,
        published_at: '2026-08-28T10:00:00Z',
        created_at: '2026-08-28T09:30:00Z',
        updated_at: '2026-08-28T10:00:00Z',
      },
    ],
  },
  {
    id: 'sug-103',
    author_id: 'usr-5',
    title: 'Community Micro-Solar Canopy & Public EV Chargers',
    description: 'Install rooftop solar arrays above municipal parking structures at Waterfront District to supply free daytime charging for public transport and neighborhood electric vehicles.',
    category_id: 'cat-3',
    neighborhood_id: 'neigh-2',
    category: SEED_CATEGORIES[2],
    neighborhood: SEED_NEIGHBORHOODS[1],
    location: { x: 1.2, y: 0.5, z: 3.8, address: 'Harbor View Deck P3', neighborhood_name: 'Waterfront District' },
    status: 'under_review',
    visibility: 'public',
    is_anonymous: false,
    support_count: 185,
    comment_count: 9,
    submitted_at: '2026-08-18T16:45:00Z',
    published_at: '2026-08-19T08:00:00Z',
    closed_at: null,
    created_at: '2026-08-18T15:00:00Z',
    updated_at: '2026-08-22T11:00:00Z',
  },
  {
    id: 'sug-104',
    author_id: 'usr-6',
    title: 'Smart LED Pedestrian Crossings & Tactile Pavements',
    description: 'Implement motion-activated high-visibility LED ground strips at school zone crossings across Greenway East for enhanced child safety during morning/evening dusk hours.',
    category_id: 'cat-4',
    neighborhood_id: 'neigh-3',
    category: SEED_CATEGORIES[3],
    neighborhood: SEED_NEIGHBORHOODS[2],
    location: { x: -2.1, y: 0.5, z: -3.5, address: 'Greenway School Boulevard', neighborhood_name: 'Greenway East' },
    status: 'completed',
    visibility: 'public',
    is_anonymous: false,
    support_count: 412,
    comment_count: 36,
    submitted_at: '2026-07-01T09:00:00Z',
    published_at: '2026-07-02T10:00:00Z',
    closed_at: '2026-08-30T17:00:00Z',
    created_at: '2026-07-01T08:30:00Z',
    updated_at: '2026-08-30T17:00:00Z',
    official_responses: [
      {
        id: 'resp-4',
        suggestion_id: 'sug-104',
        author_id: 'staff-1',
        author_name: 'Department of Public Safety',
        body: 'Installation complete across all 6 targeted school crosswalks. Traffic telemetry reports a 40% reduction in vehicle approach speeds.',
        is_published: true,
        published_at: '2026-08-30T17:00:00Z',
        created_at: '2026-08-30T16:30:00Z',
        updated_at: '2026-08-30T17:00:00Z',
      },
    ],
  },
  {
    id: 'sug-105',
    author_id: 'usr-7',
    title: 'Interactive Civic Mural & Youth Open-Air Stage',
    description: 'Establish a rotating digital and physical mural wall at Highland Park amphitheater celebrating neighborhood history and youth performances.',
    category_id: 'cat-5',
    neighborhood_id: 'neigh-5',
    category: SEED_CATEGORIES[4],
    neighborhood: SEED_NEIGHBORHOODS[4],
    location: { x: 3.2, y: 0.5, z: 1.5, address: 'Highland Community Center', neighborhood_name: 'Highland Park' },
    status: 'submitted',
    visibility: 'public',
    is_anonymous: false,
    support_count: 98,
    comment_count: 4,
    submitted_at: '2026-09-01T12:00:00Z',
    published_at: '2026-09-01T14:00:00Z',
    closed_at: null,
    created_at: '2026-09-01T11:20:00Z',
    updated_at: '2026-09-01T14:00:00Z',
  },
];
